### ISSUE TITLE
Document new interrupt specific instructions

### ISSUE THREAD

**Issue by catvec** [L-E-G/instruction-set-architecture#4]
- [ ] Set interrupt handler
- [ ] Perform interrupt
- [ ] Return from interrupt

**Comment by catvec** [comment]
Todo: 

-[ ] fix mix-up in docs between set interrupt handler and perform interrupt
- [ ] add an argument to the perform interrupt handler which will be directly passed as R1 to the interrupt handler

**Comment by catvec** [comment]
Office hours notes:

- [x] Change so that instead of having one `KEYPRESS` interrupt and then a code which indicates which key press just have a different interrupt for each key press
- [x] Change perform interrupt instruction so they don't use `R0` and `R1` to store interrupt details anymore
  - Instead store the interrupt code in a special location in DRAM (called memory mapping)
  - So the interrupt handler will always know that for example the memory location 0xDEADBEEF` contains the interrupt code
  - This means the perform interrupt instruction has to place the interrupt code at this memory location
- [x] Use a separate register to store the return address for the interrupt
- [x] Instead of a return from interrupt instruction make a "jump out of interrupt" instruction which indirectly jumps to the address stored in the separate return from interrupt link register

Comment here if you have any questions.

**Comment by rscibelli** [comment]
Question: What should we make the memory location of the interrupt code?

**Comment by catvec** [comment]
All done, good work.
